######################################################################
# Automatically generated by qmake (3.1) Wed Jun 19 23:17:31 2024
######################################################################

TEMPLATE = app
TARGET = DeliverNow
CONFIG += debug c++2a
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += Courier.h \
           CourierCompany.h \
           CourierRepository.h \
           CourierView.h \
           DeliverNow.h \
           Observer.h \
           Package.h \
           PackageRepository.h \
           Service.h \
           Signal.h \
           ui_CourierView.h \
           ui_DeliverNow.h \
           Graph.h
FORMS += CourierView.ui DeliverNow.ui
SOURCES += Courier.cpp \
           CourierCompany.cpp \
           CourierRepository.cpp \
           CourierView.cpp \
           DeliverNow.cpp \
           main.cpp \
           Package.cpp \
           PackageRepository.cpp \
           Service.cpp \
           Signal.cpp \
           Graph.cpp
QT += core gui widgets